<a href="https://colab.research.google.com/github/avantikabalaji2002/My_Projects/blob/main/309_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1 Generate a tuple from the set ["aman", "222", 777, 400.4]
my_tuple = ("aman", "222", 777, 400.4)
print(my_tuple)

('aman', '222', 777, 400.4)


In [5]:
#Q2 Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.
my_dict = {"Roll No:": "309", "Last Name:": "Balaji",
           "First Name:": "Avantika", "Date of Birth": "06-05-2002"}
print(my_dict)

{'Roll No:': '309', 'Last Name:': 'Balaji', 'First Name:': 'Avantika', 'Date of Birth': '06-05-2002'}


In [7]:
#Q3 Use rand function to generate a 2-dimensional random array with seed.
import numpy as np
np.random.seed(20)
np.random.random((2,3))

array([[0.5881308 , 0.89771373, 0.89153073],
       [0.81583748, 0.03588959, 0.69175758]])

In [12]:
#Q4 Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)
from random import seed
from random import random
seed(1)
value = random()
print(value)

number = -1234
absolute_number = abs(number)
print(absolute_number)

0.13436424411240122
1234


In [14]:
#Q5 Return a random integer N such that 20 <= N <= 90. 
import random
x = random.randint(20,90)
print(x)

52


In [41]:
#Q6 Given a population or set[11, 12, 13,14, 15]
#Return a 3 length list of unique elements without replacement.
import random
from random import shuffle
random_list = random.sample(range(11,15),3)
print(random_list)

#Shuffle the above set
random.shuffle(random_list)

#Print a random number from the set
rand_index = random.randrange(len(random_list))
new_rand = random_list[rand_index]
print("Random number from new set: "+str(new_rand))

[12, 14, 13]
Random number from new set: 12


In [44]:
#Q7 Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.
f = open("sample.txt", "r")
print(f.read())

{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 CourierNewPSMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue255;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c100000;}
{\*\listtable{\list\listtemplateid1\listhybrid{\listlevel\levelnfc0\levelnfcn0\leveljc0\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\*\levelmarker \{decimal\}.}{\leveltext\leveltemplateid1\'02\'00.;}{\levelnumbers\'01;}\fi-360\li720\lin720 }{\listname ;}\listid1}}
{\*\listoverridetable{\listoverride\listid1\listoverridecount0\ls1}}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\tx360\tx720\tx916\tx1832\tx2748\tx3664\tx4580\tx5496\tx6412\tx7328\tx8244\tx9160\tx10076\tx10480\tx10480\tx10480\tx10480\tx10480\pardeftab720\li720\fi-720\sl291\partightenfactor0
\ls1\ilvl0
\f0\fs20 \cf2 The King is Dead, Long Live The King}


In [56]:
#8 Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue.
print("Using if,elif and else: ")
number = -0.0
if number>0:
  print("Positive Number")
elif number==0:
  print("Zero")
else:
  print("Negative Number")

print("Using break and continue: ")
names = ["Dahmer", "Claire", "Trace", "Nina", "Phil"]
for name in names:
  if len(name)!=4:
    continue

  print(f"Hello, {name}")
  if name=="Phil":
      break
print("Done")

print("Using while loop")
x = 0
while(x<10):
  print(x)
  x = x+1

print("Using for loop")
for x in range(3,7):
  print(x)

Using if,elif and else: 
Zero
Using break and continue: 
Hello, Nina
Hello, Phil
Done
Using while loop
0
1
2
3
4
5
6
7
8
9
Using for loop
3
4
5
6


In [62]:
#9 Given a string "The King is Dead, Long Live The King" 
# Print the complete string
# Print first character of the string
# Print characters starting from 3rd to 5th
# Print string starting from 3rd character
# Split the words
my_string = "The King is Dead, Long Live The King"
print(my_string)
first_char = my_string[0]
print(first_char)
middle_char = my_string[3:5]
print(middle_char)
N = len(my_string)
new_string = my_string[3:N]
print(new_string)
split_string = my_string.split()
print(split_string)

The King is Dead, Long Live The King
T
 K
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [66]:
#Q10 An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements
import numpy as np
my_list = [1,4,5,8]
my_array = np.array(my_list)
print(my_array)
a = my_array[0:2]
print(a)

[1 4 5 8]
[1 4]


In [67]:
#Q11 Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).
my_array = [(1,2,3),(4,5,6)]
print(my_array)

[(1, 2, 3), (4, 5, 6)]


In [76]:
#Q12 Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
# Slice and display the 2nd row.
# Write code to display as array([2., 5.]) 
# Find the length of the array.
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a[1])
print(a[:,1])
x = len(a)
print(x)

[[1 2 3]
 [4 5 6]]
[4 5 6]
[2 5]
2


In [4]:
#Q13 Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
new_arr = np.reshape(arr,(2,5))
print("Array: ")
print(new_arr)
print("Array Transpose: ")
array_transpose = new_arr.transpose()
print(array_transpose)

Array: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Array Transpose: 
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [5]:
#Q14 Create an array from a list of 1,2 and 3.
import numpy as np
my_list = [1,2,3]
my_array = np.array(my_list)
print(my_array)


[1 2 3]


In [7]:
#Q15 Fill an array [1,2,3] with a single value [9,9,9]. 
import numpy as np
my_array = np.array([1,2,3])
new_array = np.full((1,3),9)
print(new_array)

[[9 9 9]]


In [8]:
#Q16 Sum the elements of array [2,4,5].
import numpy as np
my_array = np.array([2,4,5])
array_sum = np.sum(my_array)
print(array_sum)

11


In [9]:
#Q17 Give the products of array [77,74,75]
import numpy as np
my_array = np.array([77,74,75])
array_prod = np.prod(my_array)
print(array_prod)

427350


In [16]:
#Q18 Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.
import numpy as np
my_array = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Average:")
print(np.mean(my_array))
print("Variance:")
print(np.var(my_array))
print("Standard deviation:")
print(np.std(my_array))
print("Minimum:")
print(np.min(my_array))
print("Maximum:")
print(np.max(my_array))
print("Median:")
print(np.median(my_array))
print("Argmin:")
print(np.argmin(my_array))
print("Argmax:")
print(np.argmax(my_array))

Average:
12.461538461538462
Variance:
367.32544378698225
Standard deviation:
19.165736192147232
Minimum:
1
Maximum:
56
Median:
2.0
Argmin:
1
Argmax:
12


In [22]:
#Q19 Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
import numpy as np
my_arr = np.array([1,1,4,5,5,5,7])
print(np.unique(my_arr))

[1 4 5 7]


In [23]:
#Q20 Find dot product of two arrays [1, 2, 3]and [0, 1, 1]. 
import numpy as np
my_arr1 = np.array([1,2,3])
my_arr2 = np.array([0,1,1])
print(np.dot(my_arr1,my_arr2))

5


In [25]:
#Q21 Find the eigenvalues and eigenvectors of matrix A.
import numpy as np
from numpy.linalg import eig
my_array = np.array([[2,12],[1,-5]])
w,v = eig(my_array)
print('Eigen Value', w)
print('Eigen Vectors', v)

Eigen Value [ 3.4244289 -6.4244289]
Eigen Vectors [[ 0.99302846 -0.8184484 ]
 [ 0.11787487  0.57458003]]
