<a href="https://colab.research.google.com/github/avantikabalaji2002/My_Projects/blob/main/ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1
princ=int(input("Enter principle: "))
time = int(input("Enter time: "))
rate = int(input("Enter interest rate: "))
a = princ*(1+rate/100)*time
ci = a - princ
print(ci)

Enter principle: 1000
Enter time: 10
Enter interest rate: 4
9400.0


In [35]:
#Q2
n = int(input("Enter size: "))
x=list()
for i in range(n):
  x.append(input())
z=list()
for i in range(n):
  perc=(x.count(x[i])/n)*100
  z.append(perc)
print(z)

Enter size: 4
w
w
t

[50.0, 50.0, 25.0, 25.0]


In [34]:
#Q3
n = int(input("Enter a number: "))
x=list()
while(n!=0):
  x.append(n%2)
  n=int(n/2)
y=x[::-1]
if(y==y[::-1]):
  print("True")
else:
  print("False")


Enter a number: 5
True


In [30]:
#Q4
def checkDivisibility(n, digit) :
	return (digit != 0 and n % digit == 0)
	
def allDigitsDivide( n) :
	temp = n
	while (temp > 0) :

		digit = temp % 10
		if ((checkDivisibility(n, digit)) == False) :
			return False

		temp = temp // 10
	
	return True

n =int(input("Enter a number: ")) 

if (allDigitsDivide(n)) :
	print("Yes")
else :
	print("No" )
	


Enter a number: 128
Yes


In [5]:
#Q5
def second_largest(list):
    large= max(list)
    list.remove(large)
    large= max(list)
    return large

li=[]
n=int(input("Enter size of list "))
for i in range(0,n):
    e=int(input("Enter element of list "))
    li.append(e)

print("second largest in ",li,"is")
print(second_largest(li))            

Enter size of list 4
Enter element of list 32
Enter element of list 33
Enter element of list 0
Enter element of list 44
second largest in  [32, 33, 0, 44] is
33


In [11]:
#Q3(NumPy)
import numpy as np
cvalues = [-1, 11, 23, 31, 42, -9]
C = np.array(cvalues)
print("Values in Centigrade degrees:")
print(C)
print("Values in  Fahrenheit degrees:")
print(np.round((9*C/5 + 32),2))



Values in Centigrade degrees:
[-1 11 23 31 42 -9]
Values in  Fahrenheit degrees:
[ 30.2  51.8  73.4  87.8 107.6  15.8]


In [15]:
#Q4 Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
import numpy as np    
print("\nOriginal arrays:")
x = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [12, 13, 14, 15, 16, 17, 18, 19, 20]])
print(x)
print("\nNumber of dimensions:")
print(x.ndim)
print("Number of elements:")
print(x.size)
print("Number of bytes for each element in array:")
print(x.itemsize) 



Original arrays:
[[ 0  1  2  3  4  5  6  7  8]
 [12 13 14 15 16 17 18 19 20]]

Number of dimensions:
2
Number of elements:
18
Number of bytes for each element in array:
8


In [21]:
#Q5 Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array
import numpy as np
array_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(array_data)
print("\nThird and fourth elements of the first and second rows ")
print(array_data[0:2, 2:4])


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


In [ ]:
import random
output=list()


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print('1D Array')
print(arr)
print('\n')
arr1 = arr.reshape(2, 4)
print ('2D Array')
print (arr1)


1D Array
[1 2 3 4 5 6 7 8]


2D Array
[[1 2 3 4]
 [5 6 7 8]]
